CC = gcc
CFLAGS = -Wall -Wextra -g -pedantic
PROGS = pointers pointer_arithmetic

all: $(PROGS)

clean:
	rm -f $(PROGS) *.o *~ callgrind.out.*

pointers: pointers.c
pointer_arithmetic: pointer_arithmetic.c
